title: Lauriane Teyssier
description: AI Scientist, MS in Data Science @ Université Paris-Saclay, MS in AI @ Tsinghua University
site_title: 'Lauriane Teyssier'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: arwen-c
email: lauriane.teyssier@gmail.com
keybase_username: arwen_c

# absolute or relative
profile_picture: assets/images/pp_lolo.png